---
title: "Explanations for Panels"
output: html_document
---

Wordcloud 1:
This is a wordcloud that represents some of the most tweeted words either by an account or about a specific 
account. If the select drop down menu is on the tab "Search," then the words in this wordcloud will represent the
most tweeted words or phrases about that subject. For example, if "UW" is searched, at a given time the most commonly used 
phrase on twitter about uw would be "UW Football." The bigger a word/phrase is on this wordcloud means that it has been tweeted about more than the others. 

The second drop down option on "Select" is "User's Timeline." For the User's timeline tab, you can search any twitter handle (excluding the @), and create a wordcloud with their most commonly used words on twitter. 

The third and final drop down option is "Trending." This tab lets you select from a large number of the most trending words and phrases on Twitter. A wordcloud is then generated from the most commonly used words and phrases about that specific trend.

In addition to these, there is a slider that can allow you to change the number of tweets you would like to use for the creation of the wordcloud. The further to the right you are on the slider means the more words that will be in your wordcloud.

Wordcloud 2: 
This wordcloud has all of the same functionality as the previous wordcloud, and supports all of the dropdowns, search-bars, and sliders from the above wordcloud. The unique aspect of this wordcloud is that it splits up the words in tweets that have negative and positive connotations. The words on the top half of the wordcloud in red possess a negative connotation, and the words in the bottom half of the wordcloud in blue possess a positive connotation. 

Map: 
This is a map with twitter data on 51 of the biggest cities in the United States.The size of the dots of cities is indexed by the population of the city. When you hover over a city, you can see the most tweeted words and hashtags for that given area. This can be extremely useful in finding out what is happening right now in a city. For example, when you hover over Denver on 5/31, you can see that the top trending tweet is about the phrase "I-25" - which is extremely relevant because the I-25 freeway in Denver is shut down today because of a large accident.

Scatterplot: 
This plot shows twitter data about some of the top accounts. The x-axis is the number of followers for different accounts, and the Y-axis is dynamic and can be changed to the number of people following or the number of tweets posted. This information can be used to visualize ratios of followers to following for famous people on twitter, and how the number of tweets influences how many followers different famous people have. The hoverdata shows the x and y data, as well as the name of twitter handle.


